AnnRepApp/config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  devise_for :users

  root 'reports#index'
  # match "/users/:id/reports", :to => "reports#index", via :get

  resources :users do
    resources :reports
  end

  # old routing
  # resources :users do
  #   resources :reports do
  #     resources :parts, :sections
  #   end
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

AnnRepApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

AnnRepApp/app/models/part.rb
class Part < ApplicationRecord
  belongs_to :report
  has_many :sections, :dependent => :destroy
end

AnnRepApp/app/models/report.rb
class Report < ApplicationRecord
  has_many :parts
  belongs_to :user
end

AnnRepApp/app/models/section.rb
class Section < ApplicationRecord
  belongs_to :part
end

AnnRepApp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

AnnRepApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

AnnRepApp/app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  layout "application"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

AnnRepApp/app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @report = Report.find(params[:report_id])
    @parts = Part.where(:report_id => @report.id)
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)
    @report = Report.find(params[:report_id])
    @part.report_id = @report.id

    respond_to do |format|
      if @part.save
        format.html
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:title, :report_id)
    end
end

AnnRepApp/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]


  # GET /reports
  # GET /reports.json
  def index
    @user = current_user
    @reports = Report.where(:user_id => @user.id)
    @hello_world_props = { name: "Stranger" }
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @user = current_user
    @parts = Part.where(:report_id => @report.id)
    @menuProps = { user: @user, report: @report, parts: @parts}
  end

  # GET /reports/new
  def new
    user = current_user.id
    @report = Report.new
    puts "******* new report"
    puts @report.inspect
    date = Time.now.strftime("%d/%m/%Y %H:%M")
    @reportProps = { report: {
                        id: nil,
                        title: "This is default title",
                        header_colour: "blue",
                        footer_colour: "red",
                        footer_date: date,
                        footer_company: "This is default company",
                        user_id: user }
          }


  end

  # GET /reports/1/edit
  def edit
    @user = current_user
  end

  # POST /reports
  # POST /reports.json
  def create
    @user = current_user
    @report = Report.new(report_params)
    @report.user_id = @user.id

    puts "****** report create *****"
    puts @report.inspect

    respond_to do |format|
      if @report.save
        puts "****** report create in if *****"
        puts @report.inspect
        format.html { redirect_to root_path, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to root_path, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :header_colour, :footer_colour, :footer_date, :footer_company, :user_id)
    end
end

AnnRepApp/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
    @report = Report.find(params[:report_id])
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:title, :content, :part_id)
    end
end

AnnRepApp/app/helpers/application_helper.rb
module ApplicationHelper
end

AnnRepApp/app/helpers/parts_helper.rb
module PartsHelper
end

AnnRepApp/app/helpers/reports_helper.rb
module ReportsHelper
end

AnnRepApp/app/helpers/sections_helper.rb
module SectionsHelper
end

AnnRepApp/app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>
<span><%= link_to('Home', root_path) %></span>

AnnRepApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnnRepApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'webpack-bundle' %>
  </head>

  <body>

    <%= render 'partials/navbar' %>

    <%= yield %>
  </body>
</html>

AnnRepApp/app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

AnnRepApp/app/views/partials/_navbar.html.erb
<nav class="nav " role="navigation">
    <ul class="">
      <% if user_signed_in? %>
        <span><%= link_to('Reports', user_reports_path(current_user)) %></span>
        <span><%= link_to('Create New Report', new_user_report_path(current_user)) %></span>
      <% end %>
      <span><%= link_to('Login', new_user_session_path) %></span>
      <span><%= link_to('Sign Up', new_user_registration_path, :method => :delete) %></span>
      <span><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
      <span><%= link_to('Hello World', hello_world_path) %></span>
    </ul>
</nav>

AnnRepApp/app/views/parts/_form.html.erb
<%= form_for(part) do |f| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :report_id %>
    <%= f.text_field :report_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AnnRepApp/app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

AnnRepApp/app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.title %></td>
        <td><%= part.report %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part', new_part_path %>

AnnRepApp/app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

AnnRepApp/app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @part.title %>
</p>

<p>
  <strong>Report:</strong>
  <%= @part.report %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>

AnnRepApp/app/views/reports/_form.html.erb
<%= form_for([current_user, report]) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :header_colour %>
    <%= f.number_field :header_colour %>
  </div>

  <div class="field">
    <%= f.label :footer_colour %>
    <%= f.number_field :footer_colour %>
  </div>

  <div class="field">
    <%= f.label :footer_date %>
    <%= f.text_field :footer_date %>
  </div>

  <div class="field">
    <%= f.label :footer_company %>
    <%= f.text_field :footer_company %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AnnRepApp/app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= form_for @report, url: user_report_path(@user) do |f| %>
  <%= render 'form', f: f %>
<% end %>

AnnRepApp/app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Header colour</th>
      <th>Footer colour</th>
      <th>Footer date</th>
      <th>Footer company</th>
      <th>User ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.header_colour %></td>
        <td><%= report.footer_colour %></td>
        <td><%= report.footer_date %></td>
        <td><%= report.footer_company %></td>
        <td><%= report.user_id %></td>
        <td><%= link_to 'Show', user_report_path(@user, report) %></td>
        <td><%= link_to 'Edit', edit_user_report_path(@user, report) %></td>
        <td><%= link_to 'Destroy', user_report_path(@user, report), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to 'New Report', new_user_report_path(@user) %>
 <%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

AnnRepApp/app/views/reports/new.html.erb
<h1>New Report</h1>
<%= react_component("ReportIndex", props: @reportProps, prerender: false) %>

AnnRepApp/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>
<%= react_component("Placeholder", props:@menuProps) %>


<!-- <p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>Header colour:</strong>
  <%= @report.header_colour %>
</p>

<p>
  <strong>Footer colour:</strong>
  <%= @report.footer_colour %>
</p>

<p>
  <strong>Footer date:</strong>
  <%= @report.footer_date %>
</p>

<p>
  <strong>Footer company:</strong>
  <%= @report.footer_company %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @report.user_id %>
</p>
<%= link_to 'Edit', edit_user_report_path(@user, @report) %> |
<%= link_to 'Back', root_path %> -->

AnnRepApp/app/views/sections/_form.html.erb
<%= form_for(section) do |f| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :part_id %>
    <%= f.text_field :part_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AnnRepApp/app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

AnnRepApp/app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.content %></td>
        <td><%= section.part %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

AnnRepApp/app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

AnnRepApp/app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @section.content %>
</p>

<p>
  <strong>Part:</strong>
  <%= @section.part %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>